services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: 'npm run start:dev gateway'
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - users

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: 'npm run start:dev users'
    env_file:
      - ./apps/users/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001

volumes:
  mongodb_data:
    driver: local
