services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: 'npm run start:dev gateway'
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - rabbitmq
      - users
      - movies
      - notifications
      - payments
      - orders

  users:
    container_name: users
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: 'npm run start:dev users'
    env_file:
      - ./apps/users/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
      - 5002:5002
    depends_on:
      - mongodb
      - rabbitmq

  movies:
    container_name: movies
    build:
      context: .
      dockerfile: ./apps/movies/Dockerfile
      target: development
    command: 'npm run start:dev movies'
    env_file:
      - ./apps/movies/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 5003:5003
    depends_on:
      - mongodb
      - rabbitmq

  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: 'npm run start:dev notifications'
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - mongodb
      - rabbitmq

  payments:
    container_name: payments
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: 'npm run start:dev payments'
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5004
    depends_on:
      - mongodb
      - rabbitmq

  orders:
    container_name: orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: 'npm run start:dev orders'
    env_file:
      - ./apps/orders/.env
    volumes:
      - .:/usr/src/app
    ports:
      - 5005:5005
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
